### ISSUE TITLE
TypeError: _typeform_embed__WEBPACK_IMPORTED_MODULE_6__.makeWidget is not a function

### ISSUE THREAD

**Issue by Sugamm** [jgmullor/nuxt-typeform#1]
First of all thanks for building this wrapper.  

When I tried to install your package, I'm getting the following error. 

<img width="719" alt="Screenshot 2021-04-13 at 1 19 10 AM" src="https://user-images.githubusercontent.com/11800370/114452857-888af400-9bf6-11eb-934c-e153a9b0e571.png">

Please help!

**Comment by jgmullor** [comment]
Hi @Sugamm! Sorry I did not notice this issue you opened. Can you show how are you using it?
Thanks you!

**Comment by jgmullor** [comment]
Hello @Sugamm, I have update the [example repository](https://github.com/jgmullor/nuxt-typeform-example) to the latest Nuxt version and looks like it is working nicely =)

Maybe are you using **Send** instead of **send**?
